# Generated by Django 5.1.6 on 2025-05-07 01:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_avis_produit_alter_avis_utilisateur_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boisson',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.produit')),
                ('volume', models.PositiveIntegerField()),
            ],
            bases=('categories.produit',),
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.produit')),
                ('composition', models.CharField(max_length=255)),
            ],
            bases=('categories.produit',),
        ),
        migrations.CreateModel(
            name='Viennoiserie',
            fields=[
                ('produit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='categories.produit')),
                ('composition', models.CharField(max_length=255)),
            ],
            bases=('categories.produit',),
        ),
        migrations.RemoveField(
            model_name='produit',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='panierproduit',
            name='panier',
        ),
        migrations.RemoveField(
            model_name='panierproduit',
            name='produit',
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={},
        ),
        migrations.RemoveField(
            model_name='produit',
            name='image',
        ),
        migrations.AddField(
            model_name='commande',
            name='date_commande',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='emplacement',
            field=models.CharField(default='Indéfini', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.DeleteModel(
            name='PanierProduit',
        ),
    ]
